# Generated by Django 5.1.1 on 2024-09-16 05:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('patient', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('addr', models.CharField(blank=True, max_length=250, null=True)),
                ('job', models.CharField(blank=True, max_length=250, null=True)),
                ('age', models.IntegerField()),
                ('phone_no', models.CharField(max_length=55, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^07[02346789]\\d{7}|02[0]\\d{7}')])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=25)),
                ('martial_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single')], default='single', max_length=25)),
                ('hiv', models.BooleanField(default=False)),
                ('hcv', models.BooleanField(default=False)),
                ('hbs', models.BooleanField(default=False)),
                ('pregnancy', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('reflux_esophagitis', models.BooleanField(default=False)),
                ('xray', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('archive', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_treatment', models.CharField(choices=[('Extraction', 'Extraction'), ('Apoxtomy', 'Apoxtomy'), ('Colemectomy', 'Colemectomy'), ('RCT', 'RCT'), ('Filling', 'Filling'), ('Repair & Retreive', 'Repair & Retreive'), ('Implant', 'Implant'), ('Orthodontics', 'Orthodontics'), ('Removable Denture', 'Removable Denture'), ('Crown Metal', 'Crown Metal'), ('Crown Porcelin', 'Crown Porcelin'), ('Crown Zarconia', 'Crown Zarconia'), ('Crown Cadlcam', 'Crown Cadlcam'), ('Preflex Felxinylon', 'Preflex Felxinylon'), ('Scaling & Air Polishing', 'Scaling & Air Polishing'), ('Tooth gems', 'Tooth gems'), ('Bleach', 'Bleach'), ('Venner', 'Venner')], max_length=100)),
                ('teeths', models.CharField(max_length=250)),
                ('amount', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.treatment')),
            ],
        ),
    ]
