# Generated by Django 5.1.1 on 2025-01-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_dentallab_medicine_dailypatient_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentallab',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
