# Generated by Django 5.1.1 on 2025-01-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_dentallab_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentallab',
            name='dental_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dentallab',
            name='labratory_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
