# Generated by Django 5.1.1 on 2024-10-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('link', 'link'), ('share', 'share')], max_length=100),
        ),
    ]
